export const healthInfo = [
  {
    id: "hydration",
    title: "Hydration Consistency",
    summary: "Water intake spread across the day tends to support smoother bowel movements.",
    body: "Aim for steady hydration instead of catching up late in the evening. Pair water with meals and fiber-heavy foods. Target 8-10 glasses daily, adjusting for activity level and climate.",
  },
  {
    id: "fiber",
    title: "Fiber Balance",
    summary: "A mix of soluble and insoluble fiber can improve stool consistency and regularity.",
    body: "Add fiber gradually, especially if you are increasing legumes, oats, greens, or seeds. Too much too quickly can increase gas. Soluble fiber (oats, apples) softens stool, while insoluble fiber (whole grains, vegetables) adds bulk.",
  },
  {
    id: "routine",
    title: "Routine Helps",
    summary: "Digestive rhythm often improves when meals, sleep, and bathroom timing stay predictable.",
    body: "A regular morning routine, especially after breakfast or warm fluids, can reinforce healthy bowel timing. Your gut has its own circadian rhythm that responds to consistency.",
  },
  {
    id: "sleep",
    title: "Sleep Quality Matters",
    summary: "Poor sleep disrupts gut motility and can lead to irregular bowel patterns.",
    body: "Aim for 7-9 hours of quality sleep. Your digestive system repairs and regulates itself during sleep. Chronic sleep deprivation can slow digestion and increase inflammation.",
  },
  {
    id: "stress",
    title: "Stress Management",
    summary: "The gut-brain connection means stress directly impacts digestive health.",
    body: "High stress can cause urgency, cramping, or constipation. Practice deep breathing, meditation, or gentle exercise. Your enteric nervous system (gut brain) has more neurons than your spinal cord.",
  },
  {
    id: "movement",
    title: "Physical Activity",
    summary: "Regular movement stimulates intestinal contractions and promotes regularity.",
    body: "Even 20-30 minutes of walking daily can improve bowel function. Exercise increases blood flow to digestive organs and helps food move through your system more efficiently.",
  },
  {
    id: "probiotics",
    title: "Gut Microbiome Health",
    summary: "A diverse gut microbiome supports digestion, immunity, and mental health.",
    body: "Include fermented foods like yogurt, kefir, sauerkraut, or kimchi. Prebiotics (garlic, onions, bananas) feed beneficial bacteria. A healthy microbiome produces vitamins and protects against pathogens.",
  },
  {
    id: "meal-timing",
    title: "Meal Timing & Portions",
    summary: "When and how much you eat affects digestive comfort and regularity.",
    body: "Eating at consistent times trains your digestive system. Large meals can cause bloating and discomfort. Consider smaller, more frequent meals if you experience digestive issues.",
  },
  {
    id: "caffeine",
    title: "Caffeine Effects",
    summary: "Caffeine stimulates bowel movements but can cause urgency or loose stools.",
    body: "Coffee increases colon activity within 4 minutes of consumption. While helpful for constipation, excessive caffeine can lead to dehydration and diarrhea. Monitor your tolerance.",
  },
  {
    id: "alcohol",
    title: "Alcohol Impact",
    summary: "Alcohol disrupts gut bacteria, increases inflammation, and affects absorption.",
    body: "Even moderate drinking can alter stool consistency and frequency. Alcohol speeds up digestion, potentially causing diarrhea, and damages the intestinal lining over time.",
  },
  {
    id: "medications",
    title: "Medication Awareness",
    summary: "Many medications affect digestive function as a side effect.",
    body: "Antibiotics kill beneficial gut bacteria. Pain relievers can cause constipation or bleeding. Antacids affect nutrient absorption. Always discuss digestive side effects with your healthcare provider.",
  },
  {
    id: "red-flags",
    title: "When to See a Doctor",
    summary: "Certain symptoms require professional medical evaluation.",
    body: "Seek medical attention for: persistent blood in stool, unexplained weight loss, severe abdominal pain, chronic diarrhea or constipation lasting 2+ weeks, black or tarry stools, or sudden changes in bowel habits after age 50.",
  },
  {
    id: "bristol-scale",
    title: "Understanding the Bristol Stool Scale",
    summary: "Types 3-4 are considered ideal, indicating healthy transit time.",
    body: "Type 1-2 suggests constipation (slow transit). Type 6-7 indicates diarrhea (too fast transit). Consistency matters more than frequency. Normal range is 3 times daily to 3 times weekly.",
  },
  {
    id: "food-triggers",
    title: "Identifying Food Triggers",
    summary: "Common trigger foods vary by individual but patterns often emerge.",
    body: "Common triggers include: dairy (lactose intolerance), gluten (celiac or sensitivity), FODMAPs (fermentable carbs), spicy foods, artificial sweeteners, and high-fat foods. Keep a food diary to identify your personal triggers.",
  },
  {
    id: "mindful-eating",
    title: "Mindful Eating Practices",
    summary: "How you eat is as important as what you eat for digestive health.",
    body: "Chew thoroughly (20-30 times per bite), eat slowly, avoid distractions while eating, and don't eat when stressed. Proper chewing releases digestive enzymes and reduces gas and bloating.",
  },
];
